name: Run Alarm Check

on:
  schedule:
    - cron: '0 8 * * *'  # todos los días a las 8AM UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente también

jobs:
  run-check-near:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Adonis app
        run: |
          RESPONSE=$(curl -s -X GET "https://fc32-2800-484-8f79-47d0-819e-cf8-df4a-760c.ngrok-free.app/alarms/check?token=${{ secrets.ALARM_SECRET_TOKEN }}")
          echo "Respuesta del servidor:"
          echo "$RESPONSE"